name: Publish release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      ZAPRET_VERSION: v70.3

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Download and configuring zapret
        run: |
          ZAPRET_FILE="zapret-${{ env.ZAPRET_VERSION }}.tar.gz"
          ZAPRET_URL="https://github.com/bol-van/zapret/releases/download/${{ env.ZAPRET_VERSION }}/$ZAPRET_FILE"
          ZAPRET_FILE_TMP="/tmp/$ZAPRET_FILE"
          ZAPRET_DIR="${{ github.workspace }}/opt/zapret"

          echo Installing curl...
          sudo apt-get install -y curl

          echo Downloading zapret release...
          curl -f -L -o "$ZAPRET_FILE_TMP" "$ZAPRET_URL"

          echo Unarchive zapret release to workspace...
          tar -xvzf "$ZAPRET_FILE_TMP" --strip-components=1 -C "$ZAPRET_DIR"

          echo Downloading ipset list...
          "$ZAPRET_DIR/ipset/get_config.sh"

      - name: Create a new release
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/tags/}"
          RELEASE_FILE="${{ github.event.repository.name }}-$RELEASE_TAG.tar.gz"
          RELEASE_FILE_TMP="/tmp/$RELEASE_FILE"

          tar -czf "$RELEASE_FILE_TMP" --exclude='.git' --exclude='.github' --exclude='.gitignore' -C "${{ github.workspace }}" .
          gh release create "$RELEASE_TAG" "$RELEASE_FILE_TMP" --generate-notes
        env:
          GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
