name: Copy Release File from Zapret

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ZAPRET_VERSION: v70.3

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Download release file from zapret repository
        run: |
          sudo apt-get install -y curl
          curl -f -L -o zapret-${{ env.ZAPRET_VERSION }}.tar.gz https://github.com/bol-van/zapret/releases/download/${{ env.ZAPRET_VERSION }}/zapret-${{ env.ZAPRET_VERSION }}.tar.gz

      - name: Copy release unar file to main repository
        run: |
          mkdir -p ${{ github.workspace }}/opt/zapret
          tar -xvzf zapret-${{ env.ZAPRET_VERSION }}.tar.gz -C ${{ github.workspace }}/opt/zapret

      - name: Create an archive of repository
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/tags/}"
          RELEASE_FILE="${{ github.repository }}-${RELEASE_TAG}.tar.gz"
          tar -czf ${{ github.repository }}"-${GITHUB_REF#refs/tags/}.tar.gz --exclude='.git' --exclude='.github' -C ${{ github.workspace }} .

      - name: Create a new GitHub release
        run: |
          gh release create $RELEASE_TAG $RELEASE_FILE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
